### ISSUE TITLE
Changelog / release notes management

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2166]
### Is your feature request related to a problem?

The current way we create the release notes is just painful. We cherry pick all the valid prs, and manually annotate the PR / issue link, and if that was a fix or an enhancement.

This is error prone and boring.

### Describe the solution you'd like

It would be much cooler if each PR was coming with an entry in a file of some sort telling if the change was a bug or an enhancement, a short description, and even if that should be mentioned or not.

This would allow us to make a smoother release note crafting, and could also be enforced in CI.
There might even already some projects out there. I am open to alternatives as long as they fit our bill.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by mehabhalodiya** [comment]
Hi, @fedepaol can you close this issue? I see it is already addressed in the PR you linked above. Thanks!

**Comment by fedepaol** [comment]
@mehabhalodiya I am leaving this open as the solution is sub-optimal. By touching the release notes, we are making all the PRs conflict between each other. 

I am still not sure what is the right solution, I am inclined to say I don't like the k8s approach where the notes are in the PR itself (I'd rather have them in git), and that a possible approach could come with a per PR yaml file that contains a few items (description, category, etc) and some automation that merges them together and produces the rel notes.

This would avoid the conflicts. Not perfect, and probably too diy, but I wasn't able to find a pre-canned solution that I like (open to hear alternatives)

**Comment by fedepaol** [comment]
Closing this now, we managed to do a release with the new tool and it works fine!
